version: 0.2

env:
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: "1"
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
    DOTNET_NOLOGO: "1"
    NUGET_XMLDOC_MODE: "skip"
    NODE_OPTIONS: "--max-old-space-size=6144"
    MSBUILDDISABLENODEREUSE: "1"

phases:
  install:
    runtime-versions:
      dotnet: 8.0
      nodejs: 20
    commands:
      - echo "---- INSTALL ----"
      - dotnet --info
      - node --version
      - npm --version

  pre_build:
    commands:
      - echo "---- FRONTEND BUILD -----"
      - cd LMS_CMS_Frontend
      - npm ci --legacy-peer-deps --no-audit --no-fund
      - npm run build --prod
      - cd ..

      - echo "---- COPY FRONTEND TO BACKEND ----"
      - mkdir -p LMS_CMS_Backend/LMS_CMS/wwwroot
      - rm -rf LMS_CMS_Backend/LMS_CMS/wwwroot/*
      - cp -r LMS_CMS_Frontend/dist/lms-cms-frontend/browser/* LMS_CMS_Backend/LMS_CMS/wwwroot/

      - echo "---- BACKEND RESTORE ----"
      - dotnet restore LMS_CMS_Backend/LMS_CMS/LMS_CMS_PL.csproj

  build:
    commands:
      - echo "---- BACKEND PUBLISH ----"
      - dotnet publish LMS_CMS_Backend/LMS_CMS/LMS_CMS_PL.csproj  -c Release -o final --no-restore --verbosity minimal -p:UseSharedCompilation=false  -p:PublishReadyToRun=false  -p:DebugType=None -p:GenerateDocumentationFile=false

      - echo "---- EF MIGRATION ----"
      - dotnet ef database update  --project LMS_CMS_Backend/LMS_CMS/LMS_CMS_PL.csproj  --context Octa_DbContext --configuration Release --no-build --verbosity quiet

  post_build:
    commands:
      - echo "---- BUILD SUCCESS ----"

artifacts:
  base-directory: final
  files:
    - '**/*'

cache:
  paths:
    - '/root/.nuget/packages/**/*'
    - '/root/.npm/**/*'
