export class Conduct {
    constructor(
        public id: number = 0,
        public details: string = '',
        public date: string = '',
        public isSendSMSToParent: boolean = false,
        public conductTypeID: number = 0,
        public conductTypeEnName: string = '',
        public conductTypeArName: string = '',
        public studentID: number = 0,
        public studentArName: string = '',
        public studentEnName: string = '',
        public SchoolID: number = 0,
        public SchoolName: string = '',
        public gradeID: number = 0,
        public gradeName: string = '',
        public classroomID: number = 0,
        public classroomName: string = '',
        public procedureTypeID: number = 0,
        public procedureTypeName: string = '',
        public newFile: File | null = null,
        public file: string = "",
        public insertedByUserId: number = 0,
        public insertedAt: string = '',
    ) { }
}
