import { AnnualVacationEmployee } from "../HR/annual-vacation-employee";

export class AccountingEmployee {
    constructor(
        public id: number = 0,
        public user_Name: string = '',
        public en_name: string = '',
        public ar_name: string = '',
        public Password: string = '',
        public mobile: string = '',
        public phone: string = '',
        public email: string = '',
        public licenseNumber: string = '',
        public address: string = '',
        public nationalID: number = 0,
        public passportNumber: string = '',
        public residenceNumber: string = '',
        public birthdayDate: string = '',
        public nationality: number =0,
        public nationalityName: string = '',
        public expireDate: string = '',
        public dateOfAppointment: string = '',
        public dateOfLeavingWork: string = '',
        public monthSalary: number|null = null,
        public hasAttendance: boolean = false,
        public attendanceTime: string = '',
        public departureTime: string = '',
        public delayAllowance: number|null = null,
        public annualLeaveBalance: number|null = null,
        public casualLeavesBalance: number|null = null,
        public monthlyLeaveRequestBalance: number|null = null,
        public graduationYear: number|null = null,
        public note: string = '',
        public reasonOfLeavingID: number = 0,
        public reasonForLeavingWork: string = '',
        public departmentID: number = 0,
        public departmentName: string = '',
        public jobCategoryID: number = 0,
        public jobID: number = 0,
        public jobName: string = '',
        public academicDegreeID: number = 0,
        public academicDegreeName: string = '',
        public days:number[]=[],
        public students:number[]=[],
        public annualVacationEmployees:AnnualVacationEmployee[]=[],
        public accountNumberName: string = '',
        public accountNumberID :number =0,
        public insertedByUserId :number =0,
        public insertedAt :number =0,
    ) {}
}
