import { AnnualVacationEmployee } from "../HR/annual-vacation-employee";
import { EmployeeAttachment } from "./employee-attachment";

export class Employee {
    constructor(
        public id: number = 0,
        public user_Name: string = '',
        public en_name: string = '',
        public ar_name: string = '',
        public password: string = '',
        public email: string = '',
        public mobile: string = '',
        public phone: string = '',
        public licenseNumber: string = '',
        public expireDate: string = '',
        public address: string = '',
        public role_ID: number = 0,
        public role_Name: string = '',
        public busCompanyID: number = 0,
        public busCompanyName: string = '',
        public employeeTypeID: number = 0,
        public monthlyLeaveRequestBalance: number = 0,
        public monthlyLeaveRequestUsed: number = 0,
        public employeeTypeName: string = '',
        public files: EmployeeAttachment[] = [],
        public editedFiles: EmployeeAttachment[] = [],
        public canReceiveRequest: boolean = false,
        public canReceiveRequestFromParent: boolean = false,
        public canReceiveMessageFromParent: boolean = false,
        public isRestrictedForLoctaion: boolean = false,
        public floorsSelected: number[] = [],
        public newFloorsSelected: number[] = [],
        public deletedFloorsSelected: number[] = [],
        public locationSelected: number[] = [],
        public newLocationSelected: number[] = [],
        public deletedLocationSelected: number[] = [],
        public gradeSelected: number[] = [],
        public newGradesSelected: number[] = [],
        public deletedGradesSelected: number[] = [],
        public subjectSelected: number[] = [],
        public newSubjectsSelected: number[] = [],
        public deletedSubjectsSelected: number[] = [],
        public isSuspended: boolean = false,
        public nationalID: number = 0,
        public passportNumber: string = '',
        public residenceNumber: string = '',
        public birthdayDate: string = '',
        public nationality: number = 0,
        public nationalityName: string = '',
        public hireDate: string = '',
        public dateOfLeavingWork: string = '',
        public monthSalary: number | null = null,
        public hasAttendance: boolean = false,
        public attendanceTime: string | null = null,
        public departureTime: string | null = null,
        public delayAllowance: number | null = null,
        public annualLeaveBalance: number | null = null,
        public casualLeavesBalance: number | null = null,
        public graduationYear: number | null = null,
        public note: string = '',
        public reasonOfLeavingID: number = 0,
        public reasonForLeavingWork: string = '',
        public departmentID: number = 0,
        public departmentName: string = '',
        public jobCategoryID: number | null = null,
        public jobID: number | null = null,
        public jobName: string = '',
        public academicDegreeID: number = 0,
        public academicDegreeName: string = '',
        public days: number[] = [],
        public students: number[] = [],
        public annualVacationEmployee: AnnualVacationEmployee[] = [],
        public accountNumberName: string = '',
        public accountNumberID: number = 0,
        public insertedByUserId: number = 0,
        public insertedAt: number = 0,
    ) { }
}

