export class School {
    constructor(
        public id: number = 0,
        public name: string = '',
        public address: string = '',
        public reportHeaderOneEn: string = '',
        public reportHeaderOneAr: string = '',
        public reportHeaderTwoEn: string = '',
        public reportHeaderTwoAr: string = '',
        public reportImageFile : File|null = null,
        public reportImage : string = "",
        public maximumPeriodCountTimeTable: number = 0,
        public maximumPeriodCountRemedials: number = 0,
        public weekStartDayID: number | null = null,
        public weekEndDayID: number | null = null,
        public schoolTypeName: string = '',
        public schoolTypeID: number = 0,
        public city: string = '',
        public citySubdivision: string = '',
        public postalZone: string = '',
        public streetName: string = '',
        public buildingNumber: string = '',
        public crn: string = '',
        public clientID: string | null = null,
        public secretNumber1: string | null = null,
        public secretNumber2: string | null = null, 
        public vatNumber: string|null = null,
    ) {}
}
